/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package logiquiz;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.DriverManager;
import java.sql.SQLException;


/**
 *
 * @author rodri
 */
public class InterfacePerguntas extends javax.swing.JFrame {

    /**
     * Creates new form InterfacePerguntas
     */
    public InterfacePerguntas() {
        initComponents();
        setExtendedState(InterfaceLogin.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        AlternativaAButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        AlternativaBButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        ALternativaCButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        AlternativaDButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Pergunta 1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 80, -1, -1));

        AlternativaAButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        AlternativaAButton.setText("Alternativa A");
        getContentPane().add(AlternativaAButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 470, 180, 60));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Em python, qual será o valor de r, de acordo com o código abaixo:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 130, -1, 80));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("a) -10");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 410, -1, -1));

        AlternativaBButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        AlternativaBButton.setText("Alternativa B");
        AlternativaBButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlternativaBButtonActionPerformed(evt);
            }
        });
        getContentPane().add(AlternativaBButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 470, 180, 60));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("b) 15");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 410, -1, -1));

        ALternativaCButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ALternativaCButton.setText("Alternativa C");
        ALternativaCButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ALternativaCButtonMouseClicked(evt);
            }
        });
        ALternativaCButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ALternativaCButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ALternativaCButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 470, 180, 60));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("c) 25");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 410, -1, -1));

        AlternativaDButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        AlternativaDButton.setText("Alternativa D");
        getContentPane().add(AlternativaDButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 470, 180, 60));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("d) 30");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 410, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("n = 5");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 220, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("n1 = 5");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 250, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("r = n * n1");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 280, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AlternativaBButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlternativaBButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AlternativaBButtonActionPerformed

    private void ALternativaCButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ALternativaCButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ALternativaCButtonActionPerformed

    private void ALternativaCButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ALternativaCButtonMouseClicked
        // TODO add your handling code here:
        String sqlalternativacerta = "UPDATE `quiz`.`usuario` SET `pontos` = '10' WHERE (`idusuario` = '3');";
        SQLConnection con = new SQLConnection();
        try (Connection c2 = con.obtemConexao()) {
            PreparedStatement ps = c2.prepareStatement(sqlalternativacerta);
            ps.executeUpdate();
            ps.close();
        } catch (SQLException ex) {
            System.out.println(ex);
        } 
         
    }//GEN-LAST:event_ALternativaCButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfacePerguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfacePerguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfacePerguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfacePerguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfacePerguntas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ALternativaCButton;
    private javax.swing.JButton AlternativaAButton;
    private javax.swing.JButton AlternativaBButton;
    private javax.swing.JButton AlternativaDButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
