/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package logiquiz;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author rodri
 */
public class InterfaceRegistro extends javax.swing.JFrame {

    /**
     * Creates new form InterfaceRegistro
     */
    public InterfaceRegistro() {
        initComponents();
        setExtendedState(InterfaceRegistro.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        UserTextField = new javax.swing.JTextField();
        PasswordField = new javax.swing.JPasswordField();
        BotaoRegistrar = new javax.swing.JButton();
        BotaoVoltar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 70)); // NOI18N
        jLabel1.setText("Senha");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 410, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 70)); // NOI18N
        jLabel2.setText("Usuário");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 220, -1, -1));

        UserTextField.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        UserTextField.setText("Crie seu usuário...");
        UserTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UserTextFieldMouseClicked(evt);
            }
        });
        UserTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(UserTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 310, 550, 80));

        PasswordField.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        PasswordField.setText("Senha...");
        PasswordField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PasswordFieldMouseClicked(evt);
            }
        });
        getContentPane().add(PasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 510, 550, 80));

        BotaoRegistrar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        BotaoRegistrar.setText("Registrar");
        BotaoRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 640, 210, 70));

        BotaoVoltar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        BotaoVoltar.setText("Voltar");
        BotaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 640, 210, 70));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 96)); // NOI18N
        jLabel3.setText("Registre-se");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 60, 590, 120));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UserTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserTextFieldActionPerformed

    private void UserTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserTextFieldMouseClicked
        // TODO add your handling code here:
        if (UserTextField.getText().equals("Crie seu usuário...")) {
            UserTextField.setText("");
        }
    }//GEN-LAST:event_UserTextFieldMouseClicked

    private void PasswordFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PasswordFieldMouseClicked
        // TODO add your handling code here:
        if (PasswordField.getText().equals("Senha...")) {
            PasswordField.setText("");
        }
    }//GEN-LAST:event_PasswordFieldMouseClicked

    private void BotaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoVoltarActionPerformed
        // TODO add your handling code here:
        InterfaceLogin frame = new InterfaceLogin();
        frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotaoVoltarActionPerformed

    private void BotaoRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoRegistrarActionPerformed
        // TODO add your handling code here:
        SQLConnection con = new SQLConnection();
        try ( Connection c2 = con.obtemConexao()) {
            Statement stmt = c2.createStatement();
            String SQLInsert = "INSERT INTO db_logquiz.usuario (nome, senha) VALUES (?, ?)";
            PreparedStatement ps = c2.prepareStatement(SQLInsert);
            String nome = UserTextField.getText();
            String senha = PasswordField.getText();
            ps.setString(1, nome);
            ps.setString(2, senha);
            ps.execute();
            JOptionPane.showMessageDialog(null, "Usuario registrado com sucesso!");
            InterfaceLogin frame = new InterfaceLogin();
            frame.setVisible(true);
            this.setVisible(false);
            ps.close();
            c2.close();
            stmt.close();
        } catch (Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(null, "Erro ao criar Usuario!!");
        }
    }//GEN-LAST:event_BotaoRegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceRegistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoRegistrar;
    private javax.swing.JButton BotaoVoltar;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JTextField UserTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
