/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package logiquiz;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.Random;
import javax.swing.JOptionPane;

public class InterfacePerguntas extends javax.swing.JFrame {
    Usuario perguntas;
    String alternativaA;
    String alternativaB;
    String alternativaC;
    String alternativaD;
    

    public InterfacePerguntas(Usuario usuario) {
        initComponents();
        this.perguntas = usuario;
        setExtendedState(InterfaceLogin.MAXIMIZED_BOTH);
        Random random = new Random();

        int id = random.nextInt(50)+1;
        SQLConnection con = new SQLConnection();
        try ( Connection c2 = con.obtemConexao()) {
            DAO dao = new DAO();
            String enunciado = dao.enunciado(id);

            Integer[] idArray = {-3, -2, -1, 0};
            List<Integer> intList = Arrays.asList(idArray);
            Collections.shuffle(intList);
            intList.toArray(idArray);
            
            
            for (int i = 0;i<4;i++) {
                idArray[i] = (id*4) + idArray[i];
            }
            
            Enunciado.setText("<html><p style=\"width:600px\">" + enunciado + "</p></html>");
            alternativaA = dao.alternativas(idArray[0]);
            this.alternativaA = dao.alternativas(idArray[0]);
            System.out.println(alternativaA);
            AlternativaA.setText("<html><p style=\"width:600px\">" + alternativaA + "</p></html>");
            alternativaB = dao.alternativas(idArray[1]);
            this.alternativaB = dao.alternativas(idArray[1]);
            AlternativaB.setText("<html><p style=\"width:600px\">" + alternativaB + "</p></html>");
            alternativaC = dao.alternativas(idArray[2]);
            this.alternativaC = dao.alternativas(idArray[2]);
            AlternativaC.setText("<html><p style=\"width:600px\">" + alternativaC + "</p></html>");
            alternativaD = dao.alternativas(idArray[3]);
            AlternativaD.setText("<html><p style=\"width:600px\">" + alternativaD + "</p></html>");
            this.alternativaD = dao.alternativas(idArray[3]);

        } catch (Exception e) {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PerguntaN = new javax.swing.JLabel();
        AlternativaAButton = new javax.swing.JButton();
        Enunciado = new javax.swing.JLabel();
        AlternativaA = new javax.swing.JLabel();
        AlternativaBButton = new javax.swing.JButton();
        AlternativaB = new javax.swing.JLabel();
        AlternativaCButton = new javax.swing.JButton();
        AlternativaC = new javax.swing.JLabel();
        AlternativaDButton = new javax.swing.JButton();
        AlternativaD = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PerguntaN.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        PerguntaN.setText("Pergunta 1");
        getContentPane().add(PerguntaN, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 80, -1, -1));

        AlternativaAButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        AlternativaAButton.setText("Alternativa A");
        AlternativaAButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlternativaAButtonActionPerformed(evt);
            }
        });
        getContentPane().add(AlternativaAButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, 180, 60));

        Enunciado.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Enunciado.setText("Em python, qual será o valor de r, de acordo com o código abaixo:");
        getContentPane().add(Enunciado, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 130, -1, 80));

        AlternativaA.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        AlternativaA.setText("a) -10");
        getContentPane().add(AlternativaA, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 270, -1, -1));

        AlternativaBButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        AlternativaBButton.setText("Alternativa B");
        AlternativaBButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlternativaBButtonActionPerformed(evt);
            }
        });
        getContentPane().add(AlternativaBButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 330, 180, 60));

        AlternativaB.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        AlternativaB.setText("b) 15");
        getContentPane().add(AlternativaB, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 350, -1, -1));

        AlternativaCButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        AlternativaCButton.setText("Alternativa C");
        AlternativaCButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AlternativaCButtonMouseClicked(evt);
            }
        });
        AlternativaCButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlternativaCButtonActionPerformed(evt);
            }
        });
        getContentPane().add(AlternativaCButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 410, 180, 60));

        AlternativaC.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        AlternativaC.setText("c) 25");
        getContentPane().add(AlternativaC, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 430, -1, -1));

        AlternativaDButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        AlternativaDButton.setText("Alternativa D");
        AlternativaDButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlternativaDButtonActionPerformed(evt);
            }
        });
        getContentPane().add(AlternativaDButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 490, 180, 60));

        AlternativaD.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        AlternativaD.setText("d) 30");
        getContentPane().add(AlternativaD, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 510, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AlternativaBButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlternativaBButtonActionPerformed
        DAO dao = new DAO();
        System.out.println(alternativaB);
        if(dao.isRight(this.alternativaB) == 1) {
            dao.pontuar(perguntas);
            JOptionPane.showMessageDialog(null, "Acertou!");
        }
        else {
            JOptionPane.showMessageDialog(null, "Errou!");
        }
    }//GEN-LAST:event_AlternativaBButtonActionPerformed

    private void AlternativaCButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlternativaCButtonActionPerformed
        DAO dao = new DAO();
        System.out.println(alternativaC);
        if(dao.isRight(this.alternativaC) == 1) {
            dao.pontuar(perguntas);
            JOptionPane.showMessageDialog(null, "Acertou!");
        }
        else {
            JOptionPane.showMessageDialog(null, "Errou!");
        }
    }//GEN-LAST:event_AlternativaCButtonActionPerformed

    private void AlternativaCButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AlternativaCButtonMouseClicked
        DAO dao = new DAO();
        if(dao.isRight(this.alternativaC) == 1) {
            dao.pontuar(perguntas);
            JOptionPane.showMessageDialog(null, "Acertou!");
        }
        else {
            JOptionPane.showMessageDialog(null, "Errou!");
        }

    }//GEN-LAST:event_AlternativaCButtonMouseClicked

    private void AlternativaAButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlternativaAButtonActionPerformed
        DAO dao = new DAO();
        System.out.println(alternativaA);
        if(dao.isRight(this.alternativaA) == 1) {
            dao.pontuar(perguntas);
            JOptionPane.showMessageDialog(null, "Acertou!");
        }
        else {
            JOptionPane.showMessageDialog(null, "Errou!");
        }

    }//GEN-LAST:event_AlternativaAButtonActionPerformed

    private void AlternativaDButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlternativaDButtonActionPerformed
        DAO dao = new DAO();
        System.out.println(alternativaD);
        if(dao.isRight(this.alternativaD) == 1) {
            dao.pontuar(perguntas);
            JOptionPane.showMessageDialog(null, "Acertou!");
        }
        else {
            JOptionPane.showMessageDialog(null, "Errou!");
        }
    }//GEN-LAST:event_AlternativaDButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfacePerguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfacePerguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfacePerguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfacePerguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new InterfacePerguntas().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AlternativaA;
    private javax.swing.JButton AlternativaAButton;
    private javax.swing.JLabel AlternativaB;
    private javax.swing.JButton AlternativaBButton;
    private javax.swing.JLabel AlternativaC;
    private javax.swing.JButton AlternativaCButton;
    private javax.swing.JLabel AlternativaD;
    private javax.swing.JButton AlternativaDButton;
    private javax.swing.JLabel Enunciado;
    private javax.swing.JLabel PerguntaN;
    // End of variables declaration//GEN-END:variables
}
