/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package logiquiz;

import javax.swing.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.DriverManager;

/**
 *
 * @author Luigi
 */
public class InterfaceLogin extends javax.swing.JFrame {

    /**
     * Creates new form InterfaceLogin
     */
    public InterfaceLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotaoRegistrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        UserTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        PassTextField = new javax.swing.JPasswordField();
        BotaoConectar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotaoRegistrar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        BotaoRegistrar.setText("Registrar-se");
        BotaoRegistrar.setPreferredSize(new java.awt.Dimension(248, 62));
        BotaoRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 560, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Usuario");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 110, -1, -1));

        UserTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(UserTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 170, 600, 60));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("Senha");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 270, -1, -1));
        getContentPane().add(PassTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 330, 600, 60));

        BotaoConectar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        BotaoConectar.setText("Conectar");
        BotaoConectar.setPreferredSize(new java.awt.Dimension(248, 62));
        BotaoConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoConectarActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoConectar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 480, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoRegistrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoRegistrarActionPerformed

    private void UserTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserTextFieldActionPerformed

    private void BotaoConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoConectarActionPerformed
        SQLConnection con = new SQLConnection();
        try (Connection c = con.obtemConexao()) {
            Statement st = c.createStatement();
            String sql = "SELECT nome, senha FROM usuario WHERE nome = ? and senha = ?";
            PreparedStatement ps = c.prepareStatement(sql);
            String nome = UserTextField.getText();
            String senha = PassTextField.getText();
            ps.setString(1, nome);
            ps.setString(2, senha);
            ResultSet rs =  ps.executeQuery();
            if(rs != null && rs.next()) {
                if (rs.getString("nome").equals(UserTextField.getText()) && rs.getString("senha").equals(PassTextField.getText())) {
                    JOptionPane.showMessageDialog(null, "cuzinho de frango");
                }
                else{
                    JOptionPane.showMessageDialog(null, "piroca doce");
                }
            }
            else {
                JOptionPane.showMessageDialog(null, "piroca doce");
            }
            ps.close();
            rs.close();
            c.close();
            st.close();
                    
        }
        catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_BotaoConectarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoConectar;
    private javax.swing.JButton BotaoRegistrar;
    private javax.swing.JPasswordField PassTextField;
    private javax.swing.JTextField UserTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
