/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package logiquiz;

import javax.swing.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.DriverManager;

/**
 *
 * @author Luigi
 */
public class InterfaceLogin extends javax.swing.JFrame {

    public static String Username;
    public static String Password;
    /**
     * Creates new form InterfaceLogin
     */

    public void InsertData() {
        Username = UserTextField.getText();
        Password = PasswordField.getText();
    }
    public String getNome() {
        InsertData();
        return Username;
    }
    public InterfaceLogin() {

        initComponents();
        setExtendedState(InterfaceLogin.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotaoRegistrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        UserTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        PasswordField = new javax.swing.JPasswordField();
        BotaoConectar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotaoRegistrar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        BotaoRegistrar.setText("Registrar-se");
        BotaoRegistrar.setPreferredSize(new java.awt.Dimension(248, 62));
        BotaoRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 690, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Usuario");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 200, -1, -1));

        UserTextField.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        UserTextField.setText("Insira seu usuário aqui!");
        UserTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UserTextFieldMouseClicked(evt);
            }
        });
        UserTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(UserTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 280, 600, 60));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("Senha");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 360, -1, -1));

        PasswordField.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        PasswordField.setText("Senha...");
        PasswordField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PasswordFieldMouseClicked(evt);
            }
        });
        getContentPane().add(PasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 420, 600, 60));

        BotaoConectar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        BotaoConectar.setText("Conectar");
        BotaoConectar.setPreferredSize(new java.awt.Dimension(248, 62));
        BotaoConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoConectarActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoConectar, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 570, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 96)); // NOI18N
        jLabel3.setText("LogiQuiz");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 30, 420, 120));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoRegistrarActionPerformed
        // TODO add your handling code here:
        InterfaceRegistro frame = new InterfaceRegistro();
        frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotaoRegistrarActionPerformed

    private void UserTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserTextFieldActionPerformed

    private void BotaoConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoConectarActionPerformed
        String nome = UserTextField.getText();
        String senha = new String(PasswordField.getPassword());
        InsertData();
        try {
            Usuario usuario = new Usuario(nome, senha);
            Usuario admin = new Usuario(nome, senha);
            DAO dao = new DAO();

            if (dao.existe(usuario)) {
                JOptionPane.showMessageDialog(null, "Bem vindo, " + usuario.getNome() + "!");
                if (dao.permissao(admin)) {
                    InterfaceAdmin frame = new InterfaceAdmin();
                    frame.setVisible(true);
                    this.setVisible(false);
                } else {
                    InterfaceMenu frame = new InterfaceMenu(usuario);
                    frame.setVisible(true);
                    this.setVisible(false);
                }

            } else {
                JOptionPane.showMessageDialog(null, "Nome/senha inválida.");
            }
        } catch (Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(null, "Erro");
        }
//        SQLConnection con = new SQLConnection();
//        try (Connection c2 = con.obtemConexao()) {
//            Statement stmt = c2.createStatement();
//            String sql = "SELECT nome, senha FROM usuario WHERE nome = ? and senha = ?";
//            PreparedStatement ps = c2.prepareStatement(sql);
//            
//            ps.setString(1, nome);
//            ps.setString(2, senha);
//            ResultSet rs =  ps.executeQuery();
//            if(rs != null && rs.next()) {
//                if (rs.getString("nome").equals(UserTextField.getText()) && rs.getString("senha").equals(PasswordField.getText())) {
//                    JOptionPane.showMessageDialog(null, "Bem vindo, " + nome + "!");
//                }
//                else{
//                    JOptionPane.showMessageDialog(null, "Erro");
//                }
//            }
//            else {
//                JOptionPane.showMessageDialog(null, "Erro");
//            }
//            ps.close();
//            rs.close();
//            c2.close();
//            stmt.close();
//                    
//        }
//        catch (Exception e) {
//            System.out.println(e);
//        }
    }//GEN-LAST:event_BotaoConectarActionPerformed

    private void UserTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserTextFieldMouseClicked
        // TODO add your handling code here:
        if (UserTextField.getText().equals("Insira seu usuário aqui!")) {
            UserTextField.setText("");
        }
    }//GEN-LAST:event_UserTextFieldMouseClicked

    private void PasswordFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PasswordFieldMouseClicked
        // TODO add your handling code here:
        if (PasswordField.getText().equals("Senha...")) {
            PasswordField.setText("");
        }
    }//GEN-LAST:event_PasswordFieldMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoConectar;
    private javax.swing.JButton BotaoRegistrar;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JTextField UserTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
