/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package logiquiz;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.Random;
import javax.swing.JOptionPane;

public class InterfaceMenu extends javax.swing.JFrame {
    Usuario menu;
    /**
     * Creates new form InterfaceMenu
     */
    public InterfaceMenu(Usuario usuario) {
        this.menu = usuario;
        initComponents();
        setExtendedState(InterfaceLogin.MAXIMIZED_BOTH);
        DAO dao = new DAO();
        try {
            int pontos = dao.pontos(menu.getNome());
            PontosLabel.setText("Pontos: " + pontos);
        } catch (Exception e){
            e.printStackTrace();
        }
        String[] test = new String[5];
        int contador = 0;
        BemVindoLabel.setText("Bem vindo, " + menu.getNome());
        SQLConnection con = new SQLConnection();
        try (Connection c2 = con.obtemConexao()) {

            Statement stmt = c2.createStatement();
            String SQLTOP1 = "SELECT nome,pontos from usuario order by pontos desc limit 5;";
            ResultSet rs = stmt.executeQuery(SQLTOP1);
            while (rs.next()) {
                test[contador++] = rs.getString("nome") + " - " + rs.getInt("pontos") + " pontos";

            }
        } catch (Exception e) {
            System.out.println(e);
        }
        top1.setText(test[0]);
        top2.setText(test[1]);
        top3.setText(test[2]);
        top4.setText(test[3]);
        top5.setText(test[4]);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RankingButton = new javax.swing.JButton();
        PontosLabel = new javax.swing.JLabel();
        top1 = new javax.swing.JLabel();
        top2 = new javax.swing.JLabel();
        top3 = new javax.swing.JLabel();
        top4 = new javax.swing.JLabel();
        top5 = new javax.swing.JLabel();
        PontosLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        BemVindoLabel = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RankingButton.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        RankingButton.setText("Top-10");
        RankingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RankingButtonActionPerformed(evt);
            }
        });
        getContentPane().add(RankingButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, 450, 140));

        PontosLabel.setFont(new java.awt.Font("Tahoma", 1, 96)); // NOI18N
        PontosLabel.setText("Pontos: ");
        getContentPane().add(PontosLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, 170));

        top1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        top1.setText("1 - ");
        getContentPane().add(top1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 180, -1, -1));

        top2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        top2.setText("1 - ");
        getContentPane().add(top2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 250, -1, -1));

        top3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        top3.setText("1 - ");
        getContentPane().add(top3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 330, -1, -1));

        top4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        top4.setText("1 - ");
        getContentPane().add(top4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 390, -1, -1));

        top5.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        top5.setText("1 - ");
        getContentPane().add(top5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 460, -1, -1));

        PontosLabel1.setFont(new java.awt.Font("Tahoma", 1, 96)); // NOI18N
        PontosLabel1.setText("Rank");
        getContentPane().add(PontosLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 40, -1, 170));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        jButton2.setText("Sair");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 560, 320, 140));

        BemVindoLabel.setFont(new java.awt.Font("Tahoma", 1, 96)); // NOI18N
        BemVindoLabel.setText("Bem vindo,");
        getContentPane().add(BemVindoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, 170));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        jButton3.setText("Iniciar Quiz!");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 560, 450, 140));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RankingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RankingButtonActionPerformed
        InterfaceTop10 frame = new InterfaceTop10(menu);
        frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_RankingButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        InterfaceLogin frame = new InterfaceLogin();
        frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        System.out.println(menu.getNome());
        InterfacePerguntas frame = new InterfacePerguntas(this.menu, 1);
        frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new InterfaceMenu(usuario).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BemVindoLabel;
    private javax.swing.JLabel PontosLabel;
    private javax.swing.JLabel PontosLabel1;
    private javax.swing.JButton RankingButton;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel top1;
    private javax.swing.JLabel top2;
    private javax.swing.JLabel top3;
    private javax.swing.JLabel top4;
    private javax.swing.JLabel top5;
    // End of variables declaration//GEN-END:variables
}
